### PR TITLE
Fix IPA identifier value

### PR DESCRIPTION
**Pull request by Rozzii**

### CODE REVIEW

**Comment by Rozzii** [comment]
I think this has to go in without the ipa test, as https://github.com/Nordix/airship-dev-tools/pull/356 is still waiting to be merged. 
So I think it should go in, an then we can do the test on 356.

**Comment by fmuyassarov** [comment]
> I think this has to go in without the ipa test, as #356 is still waiting to be merged.
> So I think it should go in, an then we can do the test on 356.

True. Just wanted to check. But maybe I should do it on another PR.

**Review by fmuyassarov — APPROVED** [review]

**Pull request merged**
