### PR TITLE
Create hardening_ssh.sh

### PR DESCRIPTION
**Pull request by jan-est**
Here is the script for ssh hardening. Could you check out how we wanna do that 

Allow some specific users:
  AllowUsers [username]

Defined in: https://wiki.nordix.org/display/IN/Security

### CODE REVIEW

**Comment by nordixinfra** [comment]
Can one of the admins verify this patch?

**Comment by kanwar-saad** [comment]
add to whitelist

**Comment by kanwar-saad** [comment]
add to whitelist

**Comment by kanwar-saad** [comment]
add to whitelist

**Comment by kanwar-saad** [comment]
add to whitelist

**Comment by kanwar-saad** [comment]
add to whitelist

**Pull request merged**
