### PR TITLE
Fix openstack node image building pipeline

### PR DESCRIPTION
**Pull request by kashifest**
Fixing typo.

### CODE REVIEW

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Comment by kashifest** [comment]
It needs approval @furkatgofurov7 @smoshiur1237

**Review by fmuyassarov — COMMENTED** [review]
I think there is an indentation issue right now (I'm not sure if this will also cause an issue, but better to avoid it). You should probably move cling brackets on lines 98-102 one step to the left.

**Comment by fmuyassarov** [comment]
This one I tested in local Jenkins:

```
pipeline {
  agent { label 'airship-static-workers' }
  environment {
    AIRSHIP_CI_USER="airshipci"
    VM_KEY = "${VM_KEY}"
    RT_URL="https://artifactory.nordix.org/artifactory"
    OS_AUTH_URL="https://kna1.citycloud.com:5000"
    OS_USER_DOMAIN_NAME="CCP_Domain_37137"
    OS_PROJECT_DOMAIN_NAME="CCP_Domain_37137"
    OS_REGION_NAME="Kna1"
    OS_PROJECT_NAME="Default Project 37137"
    OS_TENANT_NAME="Default Project 37137"
    OS_AUTH_VERSION=3
    OS_IDENTITY_API_VERSION=3
    DOCKER_CMD_ENV="--env AIRSHIP_CI_USER \
      --env AIRSHIP_CI_USER_KEY=/data/id_rsa_airshipci \
      --env VM_KEY \
      --env RT_URL \
      --env OS_AUTH_URL \
      --env OS_USER_DOMAIN_NAME \
      --env OS_PROJECT_DOMAIN_NAME \
      --env OS_REGION_NAME \
      --env OS_PROJECT_NAME \
      --env OS_TENANT_NAME \
      --env OS_AUTH_VERSION \
      --env OS_IDENTITY_API_VERSION \
      --env OS_USERNAME \
      --env OS_PASSWORD "
    CURRENT_DIR = sh (
                      script: 'readlink -f "."',
                      returnStdout: true
                     ).trim()

  }
  stages {
    stage('Building node Ubuntu image'){
      options {
        timeout(time: 60, unit: 'MINUTES')
      }
      steps {
        withCredentials([usernamePassword(credentialsId: 'airshipci_city_cloud_openstack_credentials', usernameVariable: 'OS_USERNAME', passwordVariable: 'OS_PASSWORD')]) {
          withCredentials([sshUserPrivateKey(credentialsId: 'airshipci_city_cloud_ssh_keypair', keyFileVariable: 'AIRSHIP_CI_USER_KEY')]){

            /* Generate node ubuntu image */
            sh "docker run --rm \
              ${DOCKER_CMD_ENV}\
              -v ${CURRENT_DIR}:/data \
              -v ${AIRSHIP_CI_USER_KEY}:/data/id_rsa_airshipci \
              registry.nordix.org/airship/image-builder \
              /data/ci/images/gen_node_ubuntu_image.sh \
              /data/id_rsa_airshipci 1"
          }
        }
      }
    }
    stage('Building node CentOS image'){
      options {
        timeout(time: 60, unit: 'MINUTES')
      }
      steps {
        withCredentials([usernamePassword(credentialsId: 'airshipci_city_cloud_openstack_credentials', usernameVariable: 'OS_USERNAME', passwordVariable: 'OS_PASSWORD')]) {
          withCredentials([sshUserPrivateKey(credentialsId: 'airshipci_city_cloud_ssh_keypair', keyFileVariable: 'AIRSHIP_CI_USER_KEY')]){

            /* Generate node CentOS dev-env image */
            sh "docker run --rm \
              ${DOCKER_CMD_ENV}\
              -v ${CURRENT_DIR}:/data \
              -v ${AIRSHIP_CI_USER_KEY}:/data/id_rsa_airshipci \
              registry.nordix.org/airship/image-builder \
              /data/ci/images/gen_metal3_centos_image.sh \
              /data/id_rsa_airshipci 1 \
              provision_node_image_centos.sh"

          }
        }
      }
    }
    stage('Push node images to artifactory'){
      options {
        timeout(time: 60, unit: 'MINUTES')
      }
      steps {
        withCredentials([usernamePassword(credentialsId: 'infra-nordix-artifactory-api-key', usernameVariable: 'RT_USER', passwordVariable: 'RT_TOKEN')]) {
            /* Generate node CentOS dev-env image */
            sh "upload_node_image_rt.sh UBUNTU_20.04_NODE_IMAGE_K8S_v1.19.3"
            sh "upload_node_image_rt.sh CENTOS_8.2_NODE_IMAGE_K8S_v1.19.3"
        }
      } 
    }
  }
}

```

**Comment by furkatgofurov7** [comment]
Why do not we put jobs in place here to check for markdown, etc? this is overkill to look for indentation, especially in pipeline..

**Comment by kashifest** [comment]
> Why do not we put jobs in place here to check for markdown, etc? this is overkill to look for indentation, especially in pipeline..

What do you mean? We dont have any prow job here.

**Review by fmuyassarov — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
Yeah, I know, I am asking why we do not have it, do not we need the job here?

> > Why do not we put jobs in place here to check for markdown, etc? this is overkill to look for indentation, especially in pipeline..
> 
> What do you mean? We dont have any prow job here.

**Pull request merged**
