### PR TITLE
Fix image flavor variable naming

### PR DESCRIPTION
**Pull request by kashifest**
This PR fixes the image flavor variable name mismatch

### CODE REVIEW

**Comment by Jaakko-Os** [comment]
I don't see any fix here. 'image_flavor' -> 'flavor', why is the change needed?

**Comment by kashifest** [comment]
> I don't see any fix here. 'image_flavor' -> 'flavor', why is the change needed?

That is because you are not looking into the whole file probably, the default value is here, 

https://github.com/Nordix/airship-dev-tools/blob/master/ci/images/image_builder_template.json#L14

**Comment by Jaakko-Os** [comment]
> > I don't see any fix here. 'image_flavor' -> 'flavor', why is the change needed?
> 
> That is because you are not looking into the whole file probably, the default value is here,
> 
> https://github.com/Nordix/airship-dev-tools/blob/master/ci/images/image_builder_template.json#L14

That clarifies it, thanks.

**Review by Jaakko-Os — APPROVED** [review]

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
